In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
datosML=pd.read_csv(r"C:\Users\Abraham\Desktop\Solo\Bootcamp\MLproyecto\Data\Processed\datosML.csv",index_col=False)
datosML

MES  Resultado  COMERCIAL_NUM  TELEOP_NUM  CANAL_NUM  tipodeobra
0       2          0            4.0           1          1           1
1       3          0            2.0           2          2           2
2       3          0            4.0           2          2           1
3       4          0            2.0           2          2           4
4       4          0            1.0           3          1           1
...   ...        ...            ...         ...        ...         ...
1332    4          0            5.0           1          3           1
1333    4          0            5.0           9          1           1
1334    4          0            5.0           1          3           1
1335    4          0            5.0           3          3           2
1336    5          0            2.0           1          3           5

[1337 rows x 6 columns]

In [4]:
datosML.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1337 entries, 0 to 1336
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MES            1337 non-null   int64  
 1   Resultado      1337 non-null   int64  
 2   COMERCIAL_NUM  1337 non-null   float64
 3   TELEOP_NUM     1337 non-null   int64  
 4   CANAL_NUM      1337 non-null   int64  
 5   tipodeobra     1337 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 62.8 KB


In [5]:
datosML.describe()

MES    Resultado  COMERCIAL_NUM   TELEOP_NUM    CANAL_NUM  \
count  1337.000000  1337.000000    1337.000000  1337.000000  1337.000000   
mean      5.899776     0.225879       3.382947     3.305161     2.027674   
std       3.392993     0.418316       1.866810     2.782470     0.952454   
min       1.000000     0.000000       1.000000     1.000000     1.000000   
25%       3.000000     0.000000       2.000000     1.000000     1.000000   
50%       6.000000     0.000000       3.000000     2.000000     2.000000   
75%       9.000000     0.000000       5.000000     6.000000     3.000000   
max      12.000000     1.000000       7.000000    11.000000     4.000000   

        tipodeobra  
count  1337.000000  
mean      3.359761  
std       1.606022  
min       1.000000  
25%       2.000000  
50%       4.000000  
75%       5.000000  
max       5.000000

In [6]:
datosML.corr()

MES  Resultado  COMERCIAL_NUM  TELEOP_NUM  CANAL_NUM  \
MES            1.000000  -0.016207       0.043288   -0.071522   0.087715   
Resultado     -0.016207   1.000000       0.091392   -0.018108   0.048173   
COMERCIAL_NUM  0.043288   0.091392       1.000000   -0.029575   0.011716   
TELEOP_NUM    -0.071522  -0.018108      -0.029575    1.000000  -0.706171   
CANAL_NUM      0.087715   0.048173       0.011716   -0.706171   1.000000   
tipodeobra     0.086977  -0.028575      -0.027511   -0.118888   0.080097   

               tipodeobra  
MES              0.086977  
Resultado       -0.028575  
COMERCIAL_NUM   -0.027511  
TELEOP_NUM      -0.118888  
CANAL_NUM        0.080097  
tipodeobra       1.000000

# Comprobación de equilibrio de target

In [7]:
datosML["Resultado"].value_counts()

0    1035
1     302
Name: Resultado, dtype: int64

In [8]:
#Dado que se se observa un desequilibrio en nuestro target, realizaremos un oversampling para solucionarlo

from imblearn.over_sampling import RandomOverSampler

oversampler = RandomOverSampler()
X_oversampled, y_oversampled = oversampler.fit_resample(datosML.drop("Resultado", axis=1), datosML["Resultado"])

# Creamos un DataFrame con el oversampling
datosoversampled = pd.DataFrame(X_oversampled, columns=datosML.drop("Resultado", axis=1).columns)
datosoversampled["Resultado"] = y_oversampled


In [9]:
y_oversampled.value_counts()

0    1035
1    1035
Name: Resultado, dtype: int64

# Pre modelos machine learning

In [10]:
from sklearn.model_selection import cross_val_score
from sklearn import model_selection

In [11]:
X= X_oversampled
y= y_oversampled

In [12]:

validation_size = 0.20
seed = 7
X_train, X_test, y_train, y_test = model_selection.train_test_split(X,
                                                                    y,
                                                                    test_size=validation_size,
                                                                    random_state=seed)


## Fast check modelos

In [13]:
from lazypredict.Supervised import LazyClassifier
from sklearn.model_selection import train_test_split

clf= LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=None)
models, predictions= clf.fit(X_train, X_test, y_train, y_test)

100%|██████████| 29/29 [00:02<00:00, 12.90it/s]


In [14]:
print(models)

                               Accuracy  Balanced Accuracy  ROC AUC  F1 Score  \
Model                                                                           
ExtraTreesClassifier               0.83               0.83     0.83      0.83   
BaggingClassifier                  0.82               0.82     0.82      0.81   
RandomForestClassifier             0.81               0.81     0.81      0.81   
DecisionTreeClassifier             0.79               0.80     0.80      0.79   
LabelPropagation                   0.79               0.80     0.80      0.79   
LabelSpreading                     0.79               0.80     0.80      0.79   
XGBClassifier                      0.78               0.79     0.79      0.78   
ExtraTreeClassifier                0.77               0.77     0.77      0.76   
LGBMClassifier                     0.75               0.76     0.76      0.75   
NuSVC                              0.75               0.75     0.75      0.74   
KNeighborsClassifier        

## MODELO 1: LOGISTIC REGRESION

In [15]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [16]:
prediction= model.predict(X_test)


In [17]:
accuracyregression=  model.score(X_test, y_test)
accuracyregression

0.5314009661835749

In [18]:
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=10) #Parte los datos en 10 trozos para usar validación cruzada / cross validation
cv_results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring='accuracy')

msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
print(cv_results)

[0.54216867 0.59036145 0.4939759  0.51807229 0.48192771 0.56024096
 0.6        0.47272727 0.61818182 0.46666667]


## MODELO 2: RANDOM TREE

In [19]:
from sklearn.tree import DecisionTreeRegressor, plot_tree

dtr = DecisionTreeRegressor()
dtr.fit(X_train,y_train)

DecisionTreeRegressor()

In [20]:
dtrprediction= dtr.predict(X_test)

In [21]:
dtraccuracy= dtr.score (X_test, y_test)
dtraccuracy

0.3478340589265895

In [22]:
dtraccscores = cross_val_score(dtr, X, y, cv=5)
dtraccscores

array([-1.61453981, -1.02435096, -0.99858888, -0.19261553,  0.        ])

## MODELO 3: BAGGING

In [23]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier


dtc = DecisionTreeClassifier()
modelbag = BaggingClassifier(base_estimator=dtc, n_estimators=100, random_state=seed)

In [24]:
modelbag.fit(X_train, y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=100,
                  random_state=7)

In [25]:
bagpred = modelbag.predict(X_test)
bagcuracy=modelbag.score(X_test, y_test)
bagcuracy

0.821256038647343

In [26]:
bagscores = cross_val_score(modelbag, X, y, cv=5)
bagscores

array([0.66908213, 0.62318841, 0.76086957, 0.68115942, 0.73671498])

In [27]:
mean_score = bagscores.mean()
print("Mean Accuracy:", mean_score)

Mean Accuracy: 0.6942028985507247


In [28]:
# pruebas extra para validar la fiabilidad

from sklearn.metrics import precision_score, recall_score, f1_score

In [29]:
#precision 
precision = precision_score(y_test, bagpred)
precision

0.7540983606557377

In [30]:
#recall

recall = recall_score(y_test, bagpred)
recall

0.9292929292929293

In [31]:
#f1 score
f1 = f1_score(y_test, bagpred)
f1

0.8325791855203619

In [52]:
#Guardo modelo
import joblib

joblib.dump(modelbag, r"C:\Users\Abraham\Desktop\Solo\Bootcamp\MLproyecto\Model\bagging.pkl")




['C:\\Users\\Abraham\\Desktop\\Solo\\Bootcamp\\MLproyecto\\Model\\bagging.pkl']

## MODELO 4: Ada Boost

In [32]:
from sklearn.ensemble import AdaBoostClassifier

adaboost = AdaBoostClassifier()
adaboost.fit(X_train, y_train)


AdaBoostClassifier()

In [33]:
adapred=adaboost.predict(X_test)


In [34]:
adaaccuracy=adaboost.score(X_test, y_test)
adaaccuracy

0.5700483091787439

In [35]:
adaboostscores = cross_val_score(adaboost, X, y, cv=5)
adaboostscores

array([0.352657  , 0.3236715 , 0.48550725, 0.44202899, 0.47826087])

## MODELO 5: RANDOM FOREST

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)


In [37]:
rf_classifier.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [38]:
y_pred = rf_classifier.predict(X_test)


In [39]:
accuracy_randomforest = accuracy_score(y_test, y_pred)
accuracy_randomforest

0.8115942028985508

In [40]:
#Cross validation
forestscores = cross_val_score(rf_classifier, X, y, cv=5)
forestscores

array([0.65700483, 0.66183575, 0.76570048, 0.70048309, 0.71256039])

In [41]:
mean_forest=forestscores.mean()
mean_forest

0.6995169082125604

In [53]:
#Guardo modelo
import joblib

joblib.dump(rf_classifier, r"C:\Users\Abraham\Desktop\Solo\Bootcamp\MLproyecto\Model\randomforest.pkl")



['C:\\Users\\Abraham\\Desktop\\Solo\\Bootcamp\\MLproyecto\\Model\\randomforest.pkl']

## Modelo 6: Extra Trees Classifier 

In [42]:
from sklearn.ensemble import ExtraTreesClassifier

clf = ExtraTreesClassifier()

# Entrenar el modelo con tus datos de entrenamiento
clf.fit(X_train, y_train)

# Realizar predicciones en tus datos de prueba
y_pred = clf.predict(X_test)



In [43]:
# Calcular la precisión del modelo
accuracy = clf.score(X_test, y_test)
accuracy

0.821256038647343

In [44]:
#cross validation

extratreecross=cross_val_score(clf, X, y, cv=5)
extratreecross.mean()

0.7347826086956522

In [54]:
#guardo modelo

import joblib

joblib.dump(clf, r"C:\Users\Abraham\Desktop\Solo\Bootcamp\MLproyecto\Model\extratrees.pkl")

['C:\\Users\\Abraham\\Desktop\\Solo\\Bootcamp\\MLproyecto\\Model\\extratrees.pkl']

## Ensemble

<p> Combinamos los tres modelos que nos ofrecen mejores resultados de cara a testear si su ensemble nos ofrece un mejor score, establecemos votación mayoritaria como criterio</p>

In [45]:
from sklearn.ensemble import VotingClassifier

# Definir los modelos base
model1 = ExtraTreesClassifier()
model2 = RandomForestClassifier()
model3 = BaggingClassifier()

# Crear el ensemble con votación mayoritaria
ensemble = VotingClassifier(estimators=[('model1', model1), ('model2', model2), ('model3', model3)], voting='hard')

# Entrenar el ensemble
ensemble.fit(X_train, y_train)

# Obtener las predicciones del ensemble
predictions = ensemble.predict(X_test)


In [46]:
scoreensemble = ensemble.score(X_test, y_test)
scoreensemble


0.8164251207729468

In [47]:
from sklearn.metrics import balanced_accuracy_score, roc_auc_score, f1_score

# Obtener las predicciones del ensemble model
predictions = ensemble.predict(X_test)

# Calcular el Balanced Accuracy
balanced_acc = balanced_accuracy_score(y_test, predictions)

# Calcular el ROC AUC
roc_auc = roc_auc_score(y_test, predictions)

# Calcular el F1 Score
f1 = f1_score(y_test, predictions)

print("Balanced Accuracy:", balanced_acc)
print("ROC AUC:", roc_auc)
print("F1 Score:", f1)


Balanced Accuracy: 0.8202861952861953
ROC AUC: 0.8202861952861953
F1 Score: 0.8256880733944952


In [55]:
import joblib

joblib.dump(ensemble,r"C:\Users\Abraham\Desktop\Solo\Bootcamp\MLproyecto\Model\my_model.pkl")

['C:\\Users\\Abraham\\Desktop\\Solo\\Bootcamp\\MLproyecto\\Model\\my_model.pkl']

## MEJOR MODELO: Ensemble (ExtraTreesClassifier, RandomForestClassifier y BaggingClassifier - Voting)

In [48]:
import joblib

joblib.dump(ensemble, 'new_model.pkl')

['new_model.pkl']

# FEATURE IMPORTANCE

<p>Extraigo el Feature importance de los dos modelos con mejor resultado para obtener una perspectiva de la importancia de cada variable en el resultado del modelo</p>

In [49]:
#feature importance de Extratrees


# Obtener la importancia de las características
importances = clf.feature_importances_

# Crear un DataFrame con las características y su importancia
feature_importances = pd.DataFrame({'Feature': X.columns, 'Importance': importances})

# Ordenar las características por su importancia descendente
feature_importances = feature_importances.sort_values('Importance', ascending=False)

# Imprimir el ranking de importancia de las características
print(feature_importances)


         Feature  Importance
0            MES        0.37
1  COMERCIAL_NUM        0.23
2     TELEOP_NUM        0.19
4     tipodeobra        0.15
3      CANAL_NUM        0.05


In [50]:
# Obtener la importancia de las características
importances = rf_classifier.feature_importances_

# Crear un DataFrame con las características y su importancia
feature_importances = pd.DataFrame({'Feature': X.columns, 'Importance': importances})

# Ordenar las características por su importancia descendente
feature_importances = feature_importances.sort_values('Importance', ascending=False)

# Imprimir el ranking de importancia de las características
print(feature_importances)


         Feature  Importance
0            MES        0.35
1  COMERCIAL_NUM        0.22
2     TELEOP_NUM        0.20
4     tipodeobra        0.17
3      CANAL_NUM        0.06
